[2024-12-21T00:01:36.138+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-19T15:00:00+00:00 [queued]>
[2024-12-21T00:01:36.147+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-19T15:00:00+00:00 [queued]>
[2024-12-21T00:01:36.148+0900] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-21T00:01:36.161+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-19 15:00:00+00:00
[2024-12-21T00:01:36.165+0900] {standard_task_runner.py:57} INFO - Started process 1231 to run task
[2024-12-21T00:01:36.168+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'scheduled__2024-12-19T15:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpmwq2btk3']
[2024-12-21T00:01:36.171+0900] {standard_task_runner.py:85} INFO - Job 15: Subtask post_crawl
[2024-12-21T00:01:36.210+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-19T15:00:00+00:00 [running]> on host 6cc4d0fc5740
[2024-12-21T00:01:36.274+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-19T15:00:00+00:00'
[2024-12-21T00:01:36.278+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-21 00:01:36
[2024-12-21T00:01:36.532+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-21T00:01:36.582+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-21T00:01:36.814+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-21T00:01:37.017+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-21T00:01:37.304+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 2005, in post_main
    for url, job_title, company, post_title in added_data:
  File "/code/plugins/post_crawling.py", line 182, in jumpit_crawling
    with open(log_file_name, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/code/plugins/jumpit/20241221.log'
[2024-12-21T00:01:37.314+0900] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241219T150000, start_date=20241220T150136, end_date=20241220T150137
[2024-12-21T00:01:37.325+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task post_crawl ([Errno 2] No such file or directory: '/code/plugins/jumpit/20241221.log'; 1231)
[2024-12-21T00:01:37.346+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-21T00:01:37.365+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
